### ISSUE TITLE
Roadmap to version 1.0

### ISSUE THREAD

**Issue by pgjones** [python-hyper/wsproto#114]
I would like to propose that we shortly release 0.14, which feature wise includes the handshake separation and the advice around HTTP/2 WebSockets. Then we wait ~3 months to see if there are any bugs or issues to fix (especially around the HTTP/2 part). Then I think we target the 0.15 release to drop Python 2 support (I'd like to add type hinting throughout). Then again wait ~3 months for any bugs or issues and then release version 1.0. Timing wise I see this as, 0.14 in a few weeks, 0.15 in June/July and 1.0 in October. 

This is based on my view that the project is roughly 1.0 ready, which I think is a shared view.

**Comment by pgjones** [comment]
Looking into this some more, I'd like to drop support for Python 3.5 at the same time. Doing so would allow the events to be converted to dataclasses (there is a backport to 3.6) and hence allow the entire codebase to be typed. The Python 3.5 EoL is September 2020 so we would be dropping support about a year early, based on the October 1.0 target.

**Comment by Kriechi** [comment]
Fine by me - here a quick reference to the mitmproxy, which dropped py3.5 support mid last year!
https://github.com/mitmproxy/mitmproxy/issues/2266

**Comment by pgjones** [comment]
See #116.

**Comment by pgjones** [comment]
So with the merge of #116 we are close to the 0.15 release, are there any pressing features desired for that release? (Otherwise I'd target a release in early June).

**Comment by pgjones** [comment]
0.15 released (a little later than planned). Assuming it works well I think a bump to 1.0 later this year makes sense - anything missing?

**Comment by Kriechi** [comment]
@pgjones I think we are pretty close to a `v1.0.0` - anything you want to see included but not yet in a PR?
I could cut a release today or next weekend.

**Comment by pgjones** [comment]
Go for it 🎉

**Comment by Kriechi** [comment]
fixed by dafe0ca

🎉 👍 💯 🥇
