### ISSUE TITLE
Can 0.9.1 be pushed to PyPI?

### ISSUE THREAD

**Issue by merrellb** [python-hyper/wsproto#12]

**Comment by njsmith** [comment]
Even 0.9.1 is pretty buggy compared to master + my pending pull requests :-(. And I still haven't gotten around to redoing the public API to make it amenable to multi-protocol HTTP/1 + WS servers...

I've sort of been figuring that when I get back to working on WS stuff then the first thing I'll need to do is fork this package and upload to pypi under a new name, hopefully temporarily but just to make some progress... this whole "writing a new I/O lib" thing has distracted me a bit, but I will get around to it eventually :-). But... @merrellb, if you're needing this, maybe we should go ahead and get started with that now?

I actually have commit rights to this repo, but I'm not going to go merging big rewrite PRs into @jeamland's repo without @jeamland at least saying something like "yeah @njsmith you should use those commit rights to do whatever you think best" :-). And I don't have PyPI access anyway.

@jeamland: if you don't have time/interest in keeping up with this, then I bet @lukasa would be happy to accept it into the python-hyper umbrella organization? I'm happy to do the grunt-work if you want – let me know. (I guess I'd just need admin rights to this repo + on pypi; my pypi username is "njs".)

**Comment by Lukasa** [comment]
Yup, python-hyper would be happy to have this lib. 👍

**Comment by merrellb** [comment]
When working on a basic trio integration (https://github.com/python-trio/trio/issues/124) I ran into some issues with 0.9.0 (I don't quite recall but I think they were related to using h11 0.5).  I would certainly be excited to see more active development as something like hyper-ws.

**Comment by jeamland** [comment]
I've applied all of @njsmith's PRs and made a few tweaks to get the build back to green. I've called this version 0.10.0 and it's up on PyPI now.

I'm more than happy to take up @Lukasa on his offer to transfer ownership to python-hyper.

**Comment by Lukasa** [comment]
Ok @jeamland, I've just invited you to the python-hyper organisation. Feel free to do a repository transfer at any time. You may also want to add me to the PyPI maintainers for the repo (username is as my GitHub username).

Once you're on board, I'll set up some teams and permissions etc. :grin:

Welcome on board!

**Comment by njsmith** [comment]
@jeamland: awesome, thanks!
