### ISSUE TITLE
performance tests?

### ISSUE THREAD

**Issue by belm0** [python-hyper/wsproto#128]
Are there any performance tests for wsproto?

https://github.com/HyperionGray/trio-websocket/issues/127 is pointing to a performance regression on the receive side between versions 0.12.0 and 0.14.1.

**Comment by belm0** [comment]
I was able to disprove the regression using another measurement strategy, but perhaps the question on performance benchmarks stands.

**Comment by pgjones** [comment]
Sounds good. I've not seen a benchmarking (in general) solution that works in a CI system though - have you?

**Comment by belm0** [comment]
Yes, variability of the CI environment would require repeated runs and filtering to produce something to take action on.  Having a benchmark would still be a first step though, and useful for manual use (e.g. when a regression is suspect after the fact, or for feedback on performance tuning.
