### ISSUE TITLE
Consider relicensing or dual licensing.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/wsproto#13]
Currently all other python-hyper projects are MIT licensed. This is not the result of me having any particular preference for MIT over BSD, simply a matter of being the first permissive license I reached for.

It would be convenient for it to be possible to make all python-hyper projects available under the same licensing terms (though all separate licenses would need to be reproduced per their own terms). For that reason it would be nice to either relicense to MIT, or if we're attached to keeping the current license, choosing to *dual* license under MIT and BSD. Currently this is really easy because there are only two contributors to the codebase, so it'll be pretty easy to track them down and get them to agree/disagree. ;)

**Comment by njsmith** [comment]
Fine with me. Dual MIT/Apache 2 might also be worth considering, for the stronger patent guarantees that Apache 2 gives users.

**Comment by Lukasa** [comment]
I can get behind that idea too, though if we were going to do it we'd want to do it for the entire org. =)

**Comment by jeamland** [comment]
Fixed by #18
