### ISSUE TITLE
Send multi-frame messages?

### ISSUE THREAD

**Issue by jonozzz** [python-hyper/wsproto#130]
Currently I don't see any way to send a message that spans multiple frames.
Briefly looked through the code and `await self.asend(BytesMessage(data=bytes(message["bytes"])))` basically initializes a `BytesMessage` with `message_finished=True` every time. 

Is there a plan to add that? Or am I missing something?

**Comment by njsmith** [comment]
I don't see any mentions of `asend` in the wsproto source code. Are you using wsproto directly, or are you using a downstream library like trio-websocket, hypercorn, etc.?

**Comment by jonozzz** [comment]
I'm using [quart](https://gitlab.com/pgjones/quart)

```
from quart import websocket

@app.websocket('/ws')
async def ws():
     await websocket.send(b'C')
```

**Comment by jonozzz** [comment]
> I don't see any mentions of `asend` in the wsproto source code. Are you using wsproto directly, or are you using a downstream library like trio-websocket, hypercorn, etc.?

Ah, wrong project. I think the issue should go to hypercorn.

**Comment by Kriechi** [comment]
Yes quart does not depend on wsproto.
Please open this issue with either quart or hypercorn - whatever library you are using.
