### ISSUE TITLE
README mentions non-existent data_to_send()

### ISSUE THREAD

**Issue by jlaine** [python-hyper/wsproto#135]
The README states that outbound data can be retrieved using a `data_to_send()` method, but in fact the data which needs to be sent is returned directly by the `send()` method.

**Comment by Kriechi** [comment]
Thanks - this looks like a leftover from a recent API change. PRs are welcome!

**Comment by Kriechi** [comment]
Wait... which README are you referring to?

**Comment by jlaine** [comment]
Uh. I'm totally stumped I could *swear* I saw this in the README.rst but cannot find it, will keep digging and reopen if I find it!
