### ISSUE TITLE
Host not encoded with IDNA

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/wsproto#160]
copied from https://github.com/mitmproxy/mitmproxy/issues/4622

We should IDNA-encode the Host header during the WS handshake in https://github.com/python-hyper/wsproto/blob/master/src/wsproto/handshake.py#L327

**Comment by gndu91** [comment]
Is the latest change I made enough?

**Comment by pgjones** [comment]
Fixed by 2afeb33b4fd5bbc30d2c64b200a442f262a005ba
