### ISSUE TITLE
Remote IP Address

### ISSUE THREAD

**Issue by NoSuck** [python-hyper/wsproto#164]
Would it be possible for `wsproto` to provide a remote client's address?  If not, are there recommended workarounds?  Thank you.

**Comment by njsmith** [comment]
`wsproto` doesn't do any networking, so it can't do anything with IP addresses. This is something you'd need to handle in your networking layer. (E.g., by saving the address returned by `sock.accept()`.)

**Comment by NoSuck** [comment]
I see.  Thank you for confirming that I was barking up the wrong tree.

This is a nice software library, by the way--much better than that other library that basically forces your entire application to use asyncio.  Thank you for sharing it.
