### ISSUE TITLE
new release for h11 compatibility update?

### ISSUE THREAD

**Issue by pabs3** [python-hyper/wsproto#171]
@Kriechi would it be possible to get a new release of wsproto so that the h11 compatibility improvements from #169/#170 are available in a released version?

The issue has been reported in release-critical bug [Debian#1005527](https://bugs.debian.org/1005527) and this will cause the [removal of wsproto](https://tracker.debian.org/pkg/python-wsproto) and many reverse dependencies from Debian bookworm on March 29th.

As you can see in #169, OpenSUSE has also encountered this issue and added a workaround for it.

**Comment by pabs3** [comment]
Excellent, thanks for that.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by Kriechi** [comment]
@pabs3 done! https://pypi.org/project/wsproto/1.1.0/

**Comment by pabs3** [comment]
Thanks, updating the Debian package now.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
