### ISSUE TITLE
Not thread safe

### ISSUE THREAD

**Issue by maartenbreddels** [python-hyper/wsproto#186]
Hi,

I'm using flask_sock (cc @miguelgrinberg) which uses simple-websocket, which uses this project, and we found some flakeyness in our CI for [Solara](https://github.com/widgetti/solara/). 

About 1 in 5 runs on CI and 1 in 50 runs on our local machines gave corrupt websocket messages, which triggered errors in json parsing.

I believe the reason is because `FrameProtocol` is not thread safe due to `_outbound_opcode`. See 
 * https://github.com/python-hyper/wsproto/blob/main/src/wsproto/frame_protocol.py#L504

I'm not sure if this should be documented or if this can be fixed. The workaround for us now is to put a mutex around the send and close calls: 
 * https://github.com/widgetti/solara/pull/308

Do you think this is sufficient? We only call receive from the same thread, but send will only also be called from other threads.

I would love to get your opinions on this.

Regards,

Maarten

**Comment by Kriechi** [comment]
Yes, a mutex is one possible option.
Happy to review and merge a PR to mention it in the docs.
