### ISSUE TITLE
[feature] Support Compression Extensions: RFC 7692

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/wsproto#20]
Implementing [RFC 7692](https://tools.ietf.org/html/rfc7692) would be a nice feature!

**Comment by njsmith** [comment]
I think this is already implemented?

https://github.com/python-hyper/wsproto/blob/969ec1e981318dd93316869192d075848c84e670/wsproto/extensions.py#L39

**Comment by Kriechi** [comment]
Oh wow! Great! 👍 
The missing docs kinda made me not find it at first 😄

**Comment by njsmith** [comment]
Yeah, right now it's not so much that the docs are incomplete as that they just don't exist...
