### ISSUE TITLE
Python 2.7's utf-8 decoder is too permissive

### ISSUE THREAD

**Issue by jeamland** [python-hyper/wsproto#24]
I've had to disable a bunch of the autobahn tests around utf-8 handling in order to get it to pass. The reason for this is that Python 2.7's utf-8 decoder lets stuff through that it shouldn't.

Example:

```
Python 3.6.1 (default, Mar 23 2017, 16:49:06)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import binascii
>>> d = binascii.unhexlify('cebae1bdb9cf83cebcceb5eda080656469746564')
>>> d.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 11: invalid continuation byte
```

vs

```
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import binascii
>>> d = binascii.unhexlify('cebae1bdb9cf83cebcceb5eda080656469746564')
>>> d.decode('utf-8')
u'\u03ba\u1f79\u03c3\u03bc\u03b5\ud800edited'
```

I've verified that this also happens in 2.7.12. The sample data is taken from case 6.3.1 of autobahn.

If anyone knows of a way to get Python 3.6's utf-8 decoder backported to 2.7 I'm all ears.

**Comment by njsmith** [comment]
so uh... how does autobahn pass its own test suite then?

**Comment by jeamland** [comment]
https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/utf8validator.py

**Comment by njsmith** [comment]
Huh, it looks like the answer is that they actually implemented a utf8 validator in Python: https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/utf8validator.py

I also learned from this that `wsaccel` contains a utf8 validator.

What a pain.

**Comment by njsmith** [comment]
jinx

**Comment by jeamland** [comment]
So should we steal one of those? My alternative plan was to see if I can pull Python 3.6's utf-8 decoder into Python 2.7 and install it as a `utf-8-modern` codec or some such.

**Comment by njsmith** [comment]
you could call it `utf8mb4`...

Joking aside, my guess is that any plan that involves shipping C code in wsproto is going to be more painful than any plan that doesn't involve this? And we already have an optional dependency on wsaccel. But really it's whatever meets your pain tolerance I guess...

**Comment by jeamland** [comment]
autobahn's uses wsaccel's if present so I'm just nicking theirs.

**Comment by jeamland** [comment]
I'm also being sneaky and only using it when we're using Python 2.7.

**Comment by njsmith** [comment]
heh, it indeed looks like autobahn runs its own utf8 validation even on py3. quick, publish a rigged wsproto-vs-autobahn-on-py3 benchmark!
