### ISSUE TITLE
Avoid quadratic behavior on Python 2?

### ISSUE THREAD

**Issue by njsmith** [python-hyper/wsproto#28]
The `wsproto.frame_protocol.Buffer.commit` method is potentially `O(n**2)` on python 2. It's not necessarily a huge deal in practice, but in principle it could lead to some sort of DoS if someone sends a ton of small messages that all arrive in a single call to `receive_bytes`.

h11 avoids this issue by manually doing the kind of amortized resizing that python 3.4+ do by default, [see here](https://github.com/njsmith/h11/blob/05ad7a72a30e4fc3db735d85fc3553bd5d10b164/h11/_receivebuffer.py#L63). It might make sense to do something similar, or to extract that code into a common library.

**Comment by Kriechi** [comment]
Unless a potentially large user has any issues on python2.7, @pgjones and I don't feel like we should spend much time on py27 improvements. I'm happy to reconsider if anyone actually gets hit by this.
