### ISSUE TITLE
Drop Python 3.4, add PyPy

### ISSUE THREAD

**Issue by jeamland** [python-hyper/wsproto#32]
Given that I don't particularly want to blow out our Travis matrix too much but that I'd like to test PyPy, should we drop 3.4 in favour of PyPy?

**Comment by SethMichaelLarson** [comment]
Because Travis executes 5 builds at a time adding PyPy won't increase your build time.

**Comment by jeamland** [comment]
There are already 26 builds that happen as part of the wsproto CI run, 24 of which are the same six runs (unit tests, autobahn client, and autobahn server, each with wsaccel installed and not installed) over four different versions of Python (2.7, 3.4, 3.5, 3.6).

**Comment by SethMichaelLarson** [comment]
Disregard my comment, I don't use the expanding feature of Travis CI often and briefly forgot it was a thing.

**Comment by njsmith** [comment]
Ideally we should test pypy2 and pypy3 separately, too...

@lukasa: has wsproto's slightly silly matrix caused any problems for the rest of the organization so far? (Travis is vague about how they do quotas, but [in 2014 the cap was per-organization, not per-person](https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/).)

I don't really care about py34 support personally, and it never had a huge amount of community uptake; dropping support for it somewhat aggressively makes sense to me.

The other thing we might want to consider is dropping some of the WSACCEL=0 builds. They're slow, and I don't think we're getting a huge amount of value out of them. Right now, the py27+WSACCEL=0 build is the only thing testing the pure-Python utf8 validator, but the py3+WSACCEL=0 builds are doing very little beyond that.

PyPy and wsaccel is also a question: it may not work at all (historically Cython and PyPy did not get along, though they've gotten much better recently), and even if does work it may be slower than the pure python version. It's probably worth checking. If it's true that wsaccel is unhelpful, we could even explicitly not support the combination, and then that cuts in half the number of PyPy tests we need to run, *and* gives us more coverage of the WSACCEL=0 case.

**Comment by Lukasa** [comment]
Nah, the org build amounts are fine for now. I don't mind a bit of waiting for CI.

**Comment by jeamland** [comment]
Travis doesn't have a pypy3 that works right now, IIRC.

I'm happy to drop WSACCEL=1 from the common set of runs and then add a specific Python 3.6+WSACCEL=1 run?

**Comment by njsmith** [comment]
Hmm, I was assuming we'd keep WSACCEL=1 and drop some WSACCEL=0, since I guess most deployments are going to want to use wsaccel, and also the WSACCEL=1 tests are *much* faster. I'm open to the other way though – do you see some advantage?

**Comment by njsmith** [comment]
Also forgetting a working pypy on travis, sticking something like this at the top of our travis script should work:

https://github.com/njsmith/sansio_toolbelt/blob/19011fca3ec8f9ac51874d92d9d9690b0858d2fb/ci/travis.sh#L5-L20

And then used like:

https://github.com/njsmith/sansio_toolbelt/blob/19011fca3ec8f9ac51874d92d9d9690b0858d2fb/.travis.yml#L18-L23
