### ISSUE TITLE
investigate why broken autobahn test is passing

### ISSUE THREAD

**Issue by njsmith** [python-hyper/wsproto#34]
Apparently the autobahn tests 12.5.* have a bug where they send invalid utf8:

https://github.com/aaugustin/websockets/pull/178#issuecomment-302923540
https://github.com/crossbario/autobahn-testsuite/issues/71

How can we be passing these tests? It seems like a correct implementation has to fail them.

**Comment by jeamland** [comment]
The answer is because we weren't running the test in question (12.4.5). Someone by the name of @njsmith decided that running up to 12.*.4 was fine. 🙂

**Comment by njsmith** [comment]
Ah-hah! How prescient of him.

**Comment by njsmith** [comment]
It looks like passing `--cases all` to `run-autobahn-tests.py` does check everything. I guess in theory we should run that occasionally, even if it's too heavy for doing as part of CI.
