### ISSUE TITLE
Trigger events for Ping/Pong frames

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/wsproto#35]
Similar to what h2 is doing with the [PingAcknowledged](https://github.com/python-hyper/hyper-h2/blob/b6d3af15fd57eef4f6788df3babf1b9ac1902220/h2/events.py#L359) event:

Trigger an event when a Ping or Ping frame (with or without "Application data") is received.

Use case:
In @mitmproxy (an interactive intercepting HTTP, HTTP/2, WebSocket proxy) we would like to log such events, and provide the user with the application data for further use.

**Comment by njsmith** [comment]
`PingAcknowledged` is only emitted for pongs, right, not pings? Is that what you want, or...?

**Comment by Lukasa** [comment]
No, they want `PingReceived` as well.

**Comment by njsmith** [comment]
Heh, and currently we don't even expose ping/pong functionality at all. So I guess this wants a `send_ping` method, plus `PingReceived` and `PongReceived` events.

**Comment by Kriechi** [comment]
Yes, yes, and yes 👍

**Comment by agronholm** [comment]
PING is currently automatically answered with a PONG. What is the point of making this a manual process?

**Comment by Kriechi** [comment]
@agronholm Ping is answered automatically, yes.
But there is no functionality to actually send a ping.

And there is no event notification to indicate to the user that a ping+pong occurred.

**Comment by agronholm** [comment]
Ah, so what was needed was a way to send a PING, not a PONG.

**Comment by Kriechi** [comment]
Correct.

One function: `send_ping(payload)`.
And two events: `PingReceived` and `PongReceived` (both with the payload as attribute).

**Comment by agronholm** [comment]
Gotcha. Working on a PR right now.

**Comment by agronholm** [comment]
But wait, there's a `ping()` method already?

**Comment by Kriechi** [comment]
Oh, right. Then only the events are missing.

**Comment by agronholm** [comment]
PR sent (#6).

**Comment by agronholm** [comment]
This issue should be closed now.

**Comment by Kriechi** [comment]
It should have auto-closed...

**Comment by agronholm** [comment]
You typed the wrong issue number in the description of #36.
