### ISSUE TITLE
Python version support?

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/wsproto#38]
Currently the README states:
> This was written using Python 3.5. Python 3.4, 3.5 and 3.6 are being actively tested. PyPy3 will be tested once TravisCI gets it working again. Python 2.x is not supported.

But `.travis.yml` contains:
```
python:
  - "2.7"
  - "3.5"
  - "3.6"
```

I'm happy to send a PR to fix this, if someone can tell me which is supposed to be correct?

**Comment by njsmith** [comment]
The readme is out of date, trust `.travis.yml`.
