### ISSUE TITLE
h11 incompatibility

### ISSUE THREAD

**Issue by smurfix** [python-hyper/wsproto#53]
I'm trying to get wsproto to work with current h11, and I'm running into a snag.

Looking at test_no_params_extension_negotiation (in test_upgrade.py, line 678), `ext = FakeExtension(accept_response='')` is called. However, `_extension_accept` (wsproto/connection.py, line 400+) thinks that an empty parameter string is entirely valid and appends it to the header (line 422: `'%s; %s' % (name, params)`) which then blows up in `h11/_headers.py` because, surprise, a header value must not end with whitespace.

What's the reasonable thing to happen here?

**Comment by DaanDeMeyer** [comment]
Any update on this? The mitmproxy package on Arch Linux is broken because of incompatible h11 versions (wsproto still relies on h11 0.7 while h11 0.8 has been released). It would be great if this gets fixed so wsproto can switch to the latest version of h11 which would fix the issue.

**Comment by njsmith** [comment]
Probably if there are no params, then wsproto should generate a header that's just `name`, with no trailing semicolon or whitespace. Anyone want to submit a PR?

**Comment by Kriechi** [comment]
Fixed via 40d958695108368dc1098dba5af839c2ce9bd0e4
