### ISSUE TITLE
Changelog and release history

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/wsproto#72]
I was taking a look at backfilling our changelog and release information. Unfortunately we don't have any git-tags that would indicate when/where releases where made...
The only thing I found so far are the [pypi releases](https://pypi.org/project/wsproto/#history):
* 0.11.0 on December 31, 2017
* 0.10.0 on May 3, 2017
* 0.9.0 on August 24, 2016
(no changelog though...)

We do have 4 "bump version" commits which match the release dates. 
@pgjones Should we use those to add tags for the past releases?

There is also a `0.9.1` commit on November 26, 2016, but it seems this wasn't pushed to pypi.

**Comment by pgjones** [comment]
I had the tags already, and I've just pushed them. I'll see what I can do for the changelog.

**Comment by Kriechi** [comment]
fixed by 24b21f1e2e151e117b053de3f14f7a7e158936e9
