### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by belm0** [python-hyper/wsproto#73]
What pending items are TODO for next release?

**Comment by Kriechi** [comment]
I'm not aware of major blockers at the moment.
@pgjones and I discussed this - and we both want to take an in-depth look at the code base over the next 1-2 weeks - and then cut a release, most likely as version `0.12.0`.

@belm0 do you have an urgent need for a sooner release? Do you want to contribute any additional features or bugfixes to be included in the next release?

**Comment by belm0** [comment]
Thank you @Kriechi.

My project is dependent on wsproto indirectly through trio-websocket and asyncwebsockets.  @mehaase mentioned that the recent commits were important for robustness.  My project has a policy of only versioned PyPy dependencies, hence I was wondering when the next release was planned.

On Monday I'll try some local testing against wsproto master and update here.

Thank you for taking on maintenance of wsproto!

**Comment by miracle2k** [comment]
I'd like to see the h11 version range increased. 0.7. has bugs that may not affect wsproto, but affect me through other libraries!

**Comment by njsmith** [comment]
I should probably update the language on the h11 site about version pinning... we haven't been making big breaking changes in practice, and now that projects are actually using it I won't do that without warning.

**Comment by Kriechi** [comment]
v0.12.0 has landed! 🎉:thumbsup:
Check out the changelog for a summary: https://github.com/python-hyper/wsproto/blob/master/CHANGELOG.rst

**Comment by pgjones** [comment]
0.12.0 of wsproto released, it requires `h11 ~= 0.8.1`. The [CHANGELOG](https://github.com/python-hyper/wsproto/blob/master/CHANGELOG.rst) should list the important changes.
