### ISSUE TITLE
Docs: ReadTheDocs fails to render enums

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/wsproto#74]
RTD fails to render our enums properly, due to the enum34 package not being installed in their venv:
https://readthedocs.org/api/v2/build/7753054.txt:
```
WARNING: autodoc: failed to import class u'WSConnection' from module u'wsproto.connection'; the following exception was raised:
No module named enum
WARNING: autodoc: failed to import class u'Opcode' from module u'wsproto.frame_protocol'; the following exception was raised:
No module named enum
WARNING: autodoc: failed to import class u'CloseReason' from module u'wsproto.frame_protocol'; the following exception was raised:
No module named enum
WARNING: autodoc: failed to import class u'Extension' from module u'wsproto.extensions'; the following exception was raised:
No module named enum
WARNING: autodoc: failed to import data u'SUPPORTED_EXTENSIONS' from module u'wsproto.extensions'; the following exception was raised:
No module named enum
```

I think the reason is because RTD does NOT call `python setup.py install` for our package.
For comparison, RTD for hyper-h2 contains the install step: https://readthedocs.org/api/v2/build/7671154.txt

The necessary flag should be under: https://readthedocs.org/dashboard/wsproto/advanced/ at the top:  `[ ] Install your project inside a virtualenv using setup.py install`
Maybe one of the admins can enable this for us?

**Comment by njsmith** [comment]
Huh. According to https://readthedocs.org/projects/wsproto/, the rtd maintainers for wsproto appear to be... the empty set?

**Comment by njsmith** [comment]
Oh no I see, it's trying to show icons but for some reason they're coming up blank for me. It's @benno, only.

**Comment by Kriechi** [comment]
Should be fixed now - I enabled the flag to install wsproto before rendering the docs.
